# Template sensor to show the last update time of the overall sensor
# Include this in your configuration.yaml: "sensor: !include template_sensors.yaml"

- platform: template
  sensors:
    playit_last_updated:
      friendly_name: "Playit Last Updated"
      value_template: >-
        {% if states('sensor.playit_status_overall') != 'unknown' and states.sensor.playit_status_overall is not none %}
          {{ as_timestamp(states.sensor.playit_status_overall.last_updated) | timestamp_custom("%Y-%m-%d %H:%M:%S") }}
        {% else %}
          {{ states('sensor.time') }}
        {% endif %}
      icon_template: mdi:clock
